import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class CarDataService {
    constructor() {}

    makes = [
        {
            make: 'Toyota',
            models: [
                'Corolla',
                'Camry',
                'Yaris',
                'Prius',
                'Land Cruiser',
                'Fortuner',
                'Hilux',
                'Hiace',
                'RAV4',
                'Tacoma',
                'Tundra',
                '4Runner',
                'Avalon',
                'C-HR',
                'Venza',
                'Sequoia',
                'Sienna',
                'GR86',
                'Supra',
                'Mirai',
                'ProAce',
                'ProAce Verso',
                'Crown',
                'bZ4X',
                'Urban Cruiser',
                'Corolla Cross',
                'Matrix',
                'Verso',
                'Alphard',
                'Innova',
                'Avanza',
                'Aygo',
                'Etios',
                'FJ Cruiser',
                'Voxy',
                'Noah',
                'LiteAce',
                'Roomy',
                'Tank',
                'Esquire',
                'GranAce',
                'Raize',
                'Vitz',
                'Aqua',
                'Spade',
                'Passo',
                'Pixis',
                'Rush',
                'Blade',
                'Harrier',
                'Kluger',
                'Belta',
                'Probox',
                'Succeed',
                'Mark X',
                'Mark II',
                'Allion',
                'Premio',
                'Wish',
                'Allex',
                'Ipsum',
                'Corona',
                'Carina',
                'Celica',
                'Starlet',
                'Tercel',
                'Echo',
                'Cynos',
                'Duet',
                'Soluna',
                'Ractis',
                'Verossa',
                'Zelas',
                'TownAce',
                'Grand Hiace',
                'Coaster',
                'Estima',
                'Century',
                'Gaia',
                'Funcargo',
                'Granvia',
                'Previa'
            ]
        },
        {
            make: 'Honda',
            models: [
                'Civic',
                'Accord',
                'City',
                'CR-V',
                'HR-V',
                'Jazz',
                'Fit',
                'Brio',
                'Amaze',
                'WR-V',
                'Pilot',
                'Odyssey',
                'Passport',
                'Element',
                'Insight',
                'Ridgeline',
                'Clarity',
                'Legend',
                'Prelude',
                'Integra',
                'NSX',
                'S2000',
                'Stream',
                'Stepwgn',
                'Freed',
                'Elysion',
                'Shuttle',
                'Mobilio',
                'Vezel',
                'Acty',
                'Zest',
                'Life',
                'Beat',
                'Ballade',
                'Logo',
                'Ascot',
                'Domani',
                'Concerto',
                'Orthia',
                'Saber',
                'Inspire',
                'Crosstour',
                'Crossroad',
                'Avancier',
                'Lagreat',
                'FR-V',
                'Edix',
                'Partner',
                'N-Box',
                'N-One',
                'N-WGN',
                'Z',
                'That',
                'Vamos',
                'Horizon',
                'Step Bus',
                'Capa',
                'MDX',
                'CR-Z',
                'Airwave',
                'Fit Aria',
                'Torneo',
                'Spike',
                'XR-V',
                'E',
                'Civic Type R',
                'Civic Si',
                'Acty Truck',
                'Acty Van',
                'Ridgeline Black Edition',
                'ZDX',
                'S-MX',
                'Concerto',
                'City Turbo',
                'Life Dunk',
                'Today',
                'S660',
                'Honda FCX',
                'Odyssey Absolute',
                'Jazz Hybrid',
                'Civic Hybrid',
                'CR-V Hybrid',
                'Insight Hybrid',
                'Grace',
                'Crossroad',
                'Stream RSZ'
            ]
        },
        {
            make: 'Suzuki',
            models: [
                'Alto',
                'Swift',
                'Celerio',
                'Wagon R',
                'Baleno',
                'Ertiga',
                'Vitara',
                'Grand Vitara',
                'Jimny',
                'Ignis',
                'S-Cross',
                'XL6',
                'Dzire',
                'Ritz',
                'Splash',
                'Kizashi',
                'APV',
                'Carry',
                'Every',
                'Super Carry',
                'SX4',
                'Liana',
                'Cultus',
                'Cultus Crescent',
                'Esteem',
                'Forenza',
                'Verona',
                'Sidekick',
                'X-90',
                'Equator',
                'Samurai',
                'Maruti 800',
                'Maruti Omni',
                'Maruti Zen',
                'Maruti Esteem',
                'Maruti Versa',
                'Ciaz',
                'Solio',
                'Spacia',
                'Lapin',
                'Hustler',
                'Alto Lapin',
                'MR Wagon',
                'Palette',
                'Aerio',
                'Escudo',
                'Fronx',
                'XL7',
                'Sierra',
                'Vitara Brezza',
                'Cappuccino',
                'Pleo',
                'Kei',
                'Twin',
                'Xbee',
                'Jimny Sierra',
                'Landy',
                'Eeco',
                'Karimun',
                'Splash',
                'Forsa',
                'Ignis Sport',
                'SX4 S-Cross',
                'Swift Sport',
                'Swift Hybrid',
                'Alivio',
                'A-Star',
                'Revo',
                'Landy Hybrid',
                'Suzuki Mega Carry',
                'Suzuki Fun',
                'Suzuki Alto Works',
                'Suzuki Mehran',
                'Suzuki Ciaz RS',
                'Suzuki Hustler Hybrid',
                'Suzuki Lapin Chocolat',
                'Suzuki Spacia Custom',
                'Suzuki Fronte',
                'Suzuki Mighty Boy',
                'Suzuki Jimny Wide',
                'Suzuki Aerio Wagon',
                'Suzuki Splash GreenLine',
                'Suzuki Liana RXi',
                'Suzuki Khyber',
                'Suzuki Potohar',
                'Suzuki Vitara AllGrip',
                'Suzuki Xbee Hybrid',
                'Suzuki Vitara Turbo',
                'Suzuki Samurai Sierra',
                'Suzuki Baleno RS',
                'Suzuki Celerio X',
                'Suzuki Alto Turbo RS',
                'Suzuki Super Carry Pro',
                'Suzuki Swift GLX',
                'Suzuki Grand Escudo'
            ]
        },
        {
            make: 'Nissan',
            models: [
                'Altima',
                'Maxima',
                'Sentra',
                'Versa',
                'Rogue',
                'Rogue Sport',
                'Murano',
                'Pathfinder',
                'Armada',
                'Kicks',
                'Juke',
                'Qashqai',
                'X-Trail',
                'Patrol',
                'Frontier',
                'Navara',
                'Titan',
                'GT-R',
                'Z',
                '370Z',
                '350Z',
                '300ZX',
                'Sylphy',
                'Teana',
                'Bluebird',
                'Skyline',
                'Cefiro',
                'Laurel',
                'Fairlady Z',
                'Terrano',
                'Xterra',
                'Hardbody',
                'Datsun 240Z',
                'Datsun 280ZX',
                'Micra',
                'March',
                'Sunny',
                'Almera',
                'Pulsar',
                'Tiida',
                'Note',
                'Cube',
                'Figaro',
                'Stanza',
                'Prairie',
                'Axxess',
                'Cedric',
                'Gloria',
                'Cima',
                'President',
                'Stagea',
                'Elgrand',
                'Serena',
                'Largo',
                'Caravan',
                'Urvan',
                'NV200',
                'NV300',
                'NV350',
                'Advan',
                'Wingroad',
                'Primera',
                'Murano CrossCabriolet',
                'Rasheen',
                'Be-1',
                'S-Cargo',
                'Pao',
                'Leopard',
                'Bassara',
                'Rnessa',
                'Liberty',
                'Patrol Y62',
                'Safari',
                'E-NV200',
                'Leaf',
                'Ariya',
                'Dayz',
                'Roox',
                'Clio',
                'Fuga',
                'Infinity Q50',
                'Infinity QX80',
                'Infinity FX',
                'Infinity EX',
                'Infinity M35h',
                'Nissan GT-R Nismo',
                'Nismo 370Z',
                'NV400',
                'NT400 Cabstar',
                'Jonga',
                'Evalia',
                'Tino',
                'Hypermini',
                'Pino',
                'Otti',
                'Rogue Hybrid',
                'Terrano II',
                'King Cab',
                '240SX',
                '200SX',
                'Silvia',
                '180SX',
                'NX Coupe',
                'Sentra SE-R',
                'Altima Coupe',
                'Maxima Hybrid',
                'Kicks e-Power',
                'Rogue Sport Hybrid',
                'Qashqai e-Power',
                'Cedric Gran Turismo',
                'Skyline GT-R R34',
                'Skyline GT-R R33',
                'Skyline GT-R R32',
                'Skyline 400R',
                'Patrol Super Safari',
                'Pathfinder Hybrid',
                'Hardbody Truck',
                'Datsun Go+',
                'Datsun Redi-Go',
                'Datsun 510',
                'Datsun Truck',
                'Datsun Roadster',
                'R390 GT1',
                'IMk',
                'IDS',
                'Concept 2020 Vision'
            ]
        },
        {
            make: 'Mitsubishi',
            models: [
                'Lancer',
                'Lancer Evolution',
                'Outlander',
                'Outlander PHEV',
                'Eclipse',
                'Eclipse Cross',
                'Pajero',
                'Pajero Sport',
                'Montero',
                'Shogun',
                'ASX',
                'RVR',
                'Mirage',
                'Attrage',
                'Space Star',
                'Colt',
                'Colt Plus',
                'Galant',
                'Galant VR-4',
                'Grandis',
                'Chariot',
                'Chariot Grandis',
                'Diamante',
                'Sigma',
                'Debonair',
                'Minica',
                'Toppo',
                'Bravo',
                'Town Box',
                'Minicab',
                'i-MiEV',
                'i',
                'eK Wagon',
                'eK X',
                'eK Space',
                'eK Custom',
                'eK Cross',
                'Delica',
                'Delica D:5',
                'Delica Space Gear',
                'Delica Van',
                'Triton',
                'L200',
                'Strada',
                'Raider',
                'Endeavor',
                'Mighty Max',
                'Starion',
                '3000GT',
                'GTO',
                'FTO',
                'Cordia',
                'Tredia',
                'Eterna',
                'Sigma Wagon',
                'L300',
                'Canter',
                'Rosa',
                'Libero',
                'Legnum',
                'Airtrek',
                'Dignity',
                'Proudia',
                'Carisma',
                'Emeraude',
                'Lancer Cedia',
                'Lancer Fortis',
                'Lancer iO',
                'Zinger',
                'Savrin',
                'Delica Mini',
                'Galant Lambda',
                'Lancer EX',
                'Lancer Ralliart',
                'ASX Active Gear',
                'Pajero Mini',
                'Pajero Junior',
                'Pajero iO',
                'Jeep J-Series',
                'Galant GTO',
                'Minicab MiEV',
                'Outlander Sport',
                'Outlander GT',
                'Montero Limited',
                'Eclipse GT',
                'Space Runner',
                'Space Wagon',
                'Colt CZT',
                'Colt Ralliart',
                'Colt T120SS',
                'Attrage GLX',
                'Mirage G4',
                'Mirage Hatchback',
                'Lancer Evolution X',
                'Lancer Evolution IX',
                'Lancer Evolution VIII',
                'Lancer Evolution VII',
                'Lancer Evolution VI',
                'Lancer Evolution V',
                'Lancer Evolution IV',
                'Lancer Evolution III',
                'Lancer Evolution II',
                'Lancer Evolution I',
                'Galant AMG',
                'Starion Turbo',
                'Eclipse Spyder',
                'Eclipse GSX',
                'Endeavor SE',
                'Endeavor LS',
                'Delica Cargo',
                'Delica Star Wagon',
                'Canter Eco Hybrid',
                'Pajero Fieldmaster',
                'L200 Barbarian',
                'L200 Warrior',
                'Raider LS',
                'Raider DuroCross',
                'Mitsubishi Concept XR-PHEV',
                'Mitsubishi Concept GC-PHEV',
                'Mitsubishi e-Evolution Concept'
            ]
        },
        {
            make: 'Ford',
            models: [
                // Sedans and Hatchbacks
                'Focus',
                'Fiesta',
                'Fusion',
                'Mondeo',
                'Taurus',
                'Falcon',
                'Escort',
                'Ka',
                'Aspire',
                'Contour',
                'Sierra',
                'Orion',
                'Granada',
                'Pinto',
                'Tempo',
                'Fairlane',
                'Cortina',
                'Probe',
                'Capri',
                'Scorpio',
                'Laser',
                'Zephyr',
                'Crown Victoria',
                'LTD',
                'Galaxie',
                'Model T',
                'Model A',

                // SUVs and Crossovers
                'Explorer',
                'Escape',
                'Edge',
                'Bronco',
                'Bronco Sport',
                'EcoSport',
                'Expedition',
                'Everest',
                'Kuga',
                'Territory',
                'Freestyle',
                'Flex',
                'Endeavour',
                'Maverick',
                'Galaxy',
                'S-Max',
                'B-MAX',
                'C-MAX',

                // Trucks and Pickups
                'F-150',
                'F-250',
                'F-350',
                'F-450',
                'F-550',
                'F-650',
                'Ranger',
                'Ranger Raptor',
                'Maverick Truck',
                'Super Duty',
                'Courier',
                'Transit',
                'Transit Connect',
                'E-Series',
                'Lobo',
                'P-Series',
                'C-Series',
                'R-Series',
                'Aerostar',

                // Performance Cars
                'Mustang',
                'Mustang Mach 1',
                'Mustang Mach-E',
                'Shelby GT350',
                'Shelby GT500',
                'Ford GT',
                'Focus RS',
                'Focus ST',
                'Fiesta ST',
                'RS200',
                'Escort RS Cosworth',
                'Capri RS3100',
                'Thunderbird Turbo Coupe',
                'Falcon GT',
                'Falcon XR6',
                'Falcon XR8',
                'Sierra RS Cosworth',

                // Electric Vehicles
                'Mustang Mach-E',
                'F-150 Lightning',
                'E-Transit',
                'Focus Electric',
                'Explorer EV',
                'Escape Hybrid',
                'C-MAX Hybrid',
                'C-MAX Energi',
                'Mach-E GT',

                // Vans and MPVs
                'Transit',
                'Transit Custom',
                'Transit Courier',
                'Transit Connect',
                'Tourneo Custom',
                'Tourneo Courier',
                'Windstar',
                'Aerostar',
                'Freestar',
                'Galaxy',

                // Classics and Iconic Models
                'Thunderbird',
                'Galaxie 500',
                'Model T',
                'Model A',
                'Crestline',
                'Anglia',
                'Popular',
                'Deluxe',
                'Fairmont',
                'Gran Torino',
                'LTD Crown Victoria',
                'Fairlane',
                'Mercury Cougar',
                'Mercury Montego',
                'Taunus',

                // Global and Region-Specific Models
                'Ikon',
                'Falcon Ute',
                'Bantam',
                'Puma',
                'Fusion Hybrid',
                'Focus Active',
                'Mondeo Wagon',
                'Escape PHEV',
                'Everest Sport',
                'EcoSport Titanium',
                'Edge ST',
                'Ranger Wildtrak',
                'Ranger XL',
                'Territory Titanium',

                // Concepts and Limited Editions
                'GT40',
                'Shelby Cobra Concept',
                'Interceptor Concept',
                'Mustang Boss 302',
                'Mustang Bullitt',
                'Focus Electric Concept',
                'SVT Lightning',
                'Thunderbird Concept',
                'Bronco R',
                'F-150 Tremor',
                'Mustang Dark Horse'
            ]
        },
        { make: 'Chevrolet', models: ['Camaro', 'Spark', 'Sonic', 'Cruze', 'Malibu', 'Trax', 'Trailblazer', 'Colorado'] },
        {
            make: 'Kia',
            models: [
                'Rio',
                'Rio 5-Door',
                'Forte',
                'Forte Koup',
                'K5',
                'Optima',
                'Cadenza',
                'Stinger',
                'Cerato',
                'Pegas',
                'Spectra',
                'Sephia',
                'Amanti',
                'Shuma',
                'Credos',

                // SUVs and Crossovers
                'Sportage',
                'Seltos',
                'Sorento',
                'Telluride',
                'Niro',
                'Niro EV',
                'Soul',
                'Soul EV',
                'Xceed',
                'Mohave',
                'Borrego',
                'Carens',
                'Carnival',
                'Sonet',
                'Stonic',

                // Electric and Hybrid Vehicles
                'EV6',
                'EV9',
                'Niro EV',
                'Soul EV',
                'Optima Hybrid',
                'Optima Plug-In Hybrid',
                'Sportage Hybrid',
                'Sportage Plug-In Hybrid',
                'Sorento Hybrid',
                'Sorento Plug-In Hybrid',

                // Vans and MPVs
                'Carnival',
                'Sedona',
                'Grand Carnival',
                'Rondo',
                'Venga',
                'Ray',
                'Carens',
                'K2500',
                'Bongo',
                'K2700',

                // Global and Region-Specific Models
                'Picanto',
                'Morning',
                'Quoris',
                'K900',
                'Opirus',
                'Ceed',
                'ProCeed',
                'Stonic',
                'Sonet',
                'KX3',
                'KX5',
                'KX7',
                'Seltos X-Line',
                'Pegas',
                'Pride',
                'Elan',

                // Performance Models
                'Stinger GT',
                'Forte GT',
                'Ceed GT',
                'ProCeed GT',
                'Rio GT-Line',

                // Classic and Iconic Models
                'Sephia',
                'Capital',
                'Avella',
                'Concord',
                'Potentia',
                'Lotze',
                'Clarus',
                'Enterprise',
                'Retona',
                'Joice',
                'Elan',
                'Towner',

                // Concepts and Limited Editions
                'Kia EV9 Concept',
                'Kia Imagine Concept',
                'Stinger GTS',
                'Telluride Nightfall Edition',
                'Seltos Gravity Edition',
                'Soul X-Line',
                "Soul Trail'ster Concept",
                'Niro Hybrid Special Edition'
            ]
        },
        { make: 'Hyundai', models: ['Accent', 'Elantra', 'Sonata', 'Kona', 'Tucson', 'Santa Fe', 'Grand Starex', 'H-100'] },
        {
            make: 'BMW',
            models: [
                '1 Series',
                '2 Series',
                '2 Series Gran Coupe',
                '3 Series',
                '3 Series Gran Turismo',
                '4 Series',
                '4 Series Gran Coupe',
                '5 Series',
                '6 Series',
                '6 Series Gran Turismo',
                '7 Series',
                '8 Series',
                '8 Series Gran Coupe',
                'M3',
                'M4',
                'M5',
                'M6',
                'M8',
                'Alpina B7',
                'i3',
                'i4',
                'i5',
                'i7',
                'Z3',
                'Z4',
                'Z8',
                '2002',
                'E30',
                'E36 Compact',
                'E21',
                'E12',
                'F10',

                // SUVs and Crossovers
                'X1',
                'X2',
                'X3',
                'X4',
                'X5',
                'X6',
                'X7',
                'XM',
                'iX',
                'iX1',
                'iX3',
                'iX5 Hydrogen',
                'ActiveHybrid X6',
                'X5 M',
                'X6 M',
                'X7 M60i',
                'X3 M',

                // Electric and Hybrid Models
                'i3',
                'i4',
                'i5',
                'i7',
                'iX',
                'iX3',
                'i8',
                'iX5 Hydrogen',
                '330e',
                '530e',
                '745e',
                'X5 xDrive45e',
                'X3 xDrive30e',

                // Sports Cars and Performance Models
                'M2',
                'M3',
                'M4',
                'M5',
                'M6',
                'M8',
                'Z3 M',
                'Z4 M',
                'Alpina B8',
                'Alpina XB7',
                '1 Series M Coupe',
                'M3 Touring',
                'M4 CSL',
                'M5 Competition',
                'M8 Competition',
                'M240i',
                '330i M Sport',

                // Classic Models
                '2002',
                '3.0 CSL',
                'E9',
                'E30 M3',
                'Z8',
                '507 Roadster',
                'Isetta',
                'E28',
                'E34',
                'E39',
                'E46',
                'New Six',
                'E92',
                'E21',
                'E36',
                'BMW 8 Series (E31)',

                // Luxury Models
                '7 Series',
                '8 Series',
                'Alpina B7',
                'i7',
                'M760Li',
                '750Li',
                '745Le',
                '850Ci',
                'i8 Roadster',

                // Global and Region-Specific Models
                '3 Series Compact',
                '5 Series E60',
                'X1 Long Wheelbase',
                '3 Series Li',
                '5 Series Li',
                'Gran Coupe Series',
                'BMW ActiveHybrid 5',
                'X4 M40i',
                'X5 xDrive50e',
                '2 Series Active Tourer',

                // Concepts and Limited Editions
                'Vision M NEXT',
                'BMW Hommage Series',
                'Garmisch',
                'i Vision Dee',
                '3.0 CSL Hommage',
                'M4 GTS',
                'Z4 Zagato',
                'X5 Le Mans',
                'M3 CRT',
                'M5 CS',
                'M850i Night Sky Edition'
            ]
        },
        {
            make: 'Mercedes-Benz',
            models: [
                'A-Class',
                'A-Class Sedan',
                'B-Class',
                'C-Class',
                'C-Class Sedan',
                'C-Class Coupe',
                'C-Class Cabriolet',
                'E-Class',
                'E-Class Sedan',
                'E-Class Coupe',
                'E-Class Cabriolet',
                'S-Class',
                'S-Class Sedan',
                'S-Class Coupe',
                'S-Class Cabriolet',
                'CLA-Class',
                'CLA Coupe',
                'CLS-Class',
                'CLS Coupe',
                'AMG GT 4-Door',
                'AMG GT',
                'AMG GT Roadster',
                'AMG C 63',
                'AMG E 63',
                'AMG S 63',
                'AMG S 65',

                // SUVs and Crossovers
                'GLA-Class',
                'GLA SUV',
                'GLB-Class',
                'GLB SUV',
                'GLC-Class',
                'GLC SUV',
                'GLC Coupe',
                'GLE-Class',
                'GLE SUV',
                'GLE Coupe',
                'GLS-Class',
                'GLS SUV',
                'G-Class',
                'G-Wagon',
                'EQB',
                'EQS SUV',
                'EQC',
                'EQE',
                'G-Class AMG',
                'AMG GLE 63',
                'AMG G-Class',

                // Electric and Hybrid Vehicles
                'EQS',
                'EQS Sedan',
                'EQE',
                'EQB',
                'EQC',
                'EQV',
                'EQG',
                'S580e',
                'C300e',
                'S500e',
                'GLE 350e',
                'GLC 300e',
                'A250e',
                'B250e',
                'E-Class Plug-In Hybrid',
                'S-Class Plug-In Hybrid',

                // Sports Cars and Performance Models
                'AMG GT',
                'AMG GT Roadster',
                'AMG GT S',
                'AMG GT Black Series',
                'SL-Class',
                'SL Roadster',
                'SLS AMG',
                'AMG C 63',
                'AMG E 63',
                'AMG S 63',
                'AMG GTR',
                'AMG GT4',
                'Mercedes-Benz 190E',
                'Mercedes-Benz SLR McLaren',

                // Classic and Iconic Models
                '300SL Gullwing',
                'Mercedes-Benz 600',
                'W123',
                'W124',
                'W126',
                'W140',
                '190E',
                'W201',
                'SLS AMG',
                'Pagoda SL',
                'Mercedes-Benz 280SE',
                'Mercedes-Benz 500SEL',

                // Vans and MPVs
                'Metris',
                'V-Class',
                'Vito',
                'Viano',
                'Marco Polo',
                'Tourer',
                'M-Class',
                'R-Class',
                'V-Class Marco Polo',

                // Commercial and Heavy Duty
                'Sprinter',
                'Sprinter Van',
                'Sprinter Chassis Cab',
                'Vito Van',
                'Econic',
                'Zetros',
                'Actros',
                'Atego',

                // Global and Region-Specific Models
                'S-Class Maybach',
                'Maybach GLS',
                'Maybach S-Class',
                'A-Class Sedan LWB',
                'V-Class LWB',
                'GLA LWB',
                'GLB LWB',
                'GLC LWB',
                'GLS LWB',
                'E-Class LWB',

                // Concepts and Limited Editions
                'Vision EQS',
                'Vision Maybach 6',
                'Mercedes-Benz Concept Car',
                'Concept X-Class',
                'Concept GLB',
                'Mercedes-Benz EQ Silver Arrow',
                'AMG Project One',
                'Mercedes-Benz EQA',
                'Mercedes-Benz EQS SUV',
                'AMG Vision GT',

                'AMG EQS',
                'AMG EQE',
                'EQX',
                'EQXX',
                'G-Class EQ'
            ]
        },
        {
            make: 'Audi',
            models: [
                'A1',
                'A3',
                'A3 Sedan',
                'A4',
                'A4 Sedan',
                'A5',
                'A5 Coupe',
                'A5 Cabriolet',
                'A6',
                'A6 Sedan',
                'A7',
                'A7 Sedan',
                'A8',
                'A8 Sedan',
                'S3',
                'S4',
                'S5',
                'S6',
                'S7',
                'S8',
                'RS3',
                'RS4',
                'RS5',
                'RS6',
                'RS7',
                'Q2',
                'Q3',
                'Q5',
                'Q7',
                'Q8',
                'Q8 e-tron',
                'Q3 Sportback',
                'RS Q3',
                'RS Q5',
                'RS Q7',
                'RS Q8',

                // SUVs and Crossovers
                'Q2',
                'Q3',
                'Q5',
                'Q7',
                'Q8',
                'Q8 e-tron',
                'Q3 Sportback',
                'Q4 e-tron',
                'Q5 Sportback',
                'Q7 Sportback',
                'Q3 TFSI',
                'RS Q3',
                'RS Q5',

                // Electric and Hybrid Vehicles
                'e-tron',
                'e-tron GT',
                'e-tron S',
                'e-tron Sportback',
                'Q4 e-tron',
                'Q4 e-tron Sportback',
                'A3 e-tron',
                'A6 e-tron',
                'A7 e-tron',
                'A8 e-tron',
                'Q5 e-tron',
                'RS e-tron GT',
                'RS Q8 e-tron',

                // Sports Cars and Performance Models
                'TT',
                'TT Coupe',
                'TT Roadster',
                'R8',
                'R8 Coupe',
                'R8 Spyder',
                'RS5',
                'RS7',
                'RS3',
                'S3',
                'S4',
                'S5',
                'S6',
                'S7',
                'S8',
                'RS Q3',
                'RS Q5',
                'RS Q7',
                'RS Q8',
                'S Q3',
                'S Q5',

                // Classic and Iconic Models
                'Audi 80',
                'Audi 100',
                'Audi 200',
                'Audi Quattro',
                'Audi 5000',
                'Audi Coupe',
                'Audi V8',
                'Audi 90',
                'Audi 200 Turbo',
                'Audi A4 B5',
                'Audi S2',
                'Audi 100 Avant',

                // Station Wagons and Estates
                'A4 Avant',
                'A6 Avant',
                'A7 Avant',
                'RS4 Avant',
                'RS6 Avant',
                'A3 Sportback',
                'A4 Allroad',
                'A6 Allroad',
                'RS6 Avant',
                'RS7 Avant',

                // Global and Region-Specific Models
                'A1 Sportback',
                'A2',
                'S3 Sedan',
                'S5 Sportback',
                'Q3 RS',
                'Q5 RS',
                'RS Q7',
                'S4 Avant',

                // Concepts and Limited Editions
                'Audi AI:ME',
                'Audi AI:Trail',
                'Audi Q4 e-tron',
                'Audi RS e-tron GT',
                'Audi Skysphere',
                'Audi Grandsphere',
                'Audi Urbansphere',
                'Audi e-tron GT Concept',
                'Audi RS 7 Avant',

                // Future Models
                'Audi Q6 e-tron',
                'Audi Q8 e-tron GT',
                'Audi Q7 Hybrid',
                'RS Q4 e-tron',
                'RS5 e-tron',
                'Audi A9 e-tron',
                'Audi AI:Race',
                'Audi SQ7',
                'Audi S8 Plus'
            ]
        },
        {
            make: 'Volkswagen',
            models: [
                'Polo',
                'Golf',
                'Golf GTI',
                'Golf R',
                'Golf Variant',
                'Passat',
                'Passat Sedan',
                'Arteon',
                'Arteon Shooting Brake',
                'Jetta',
                'Jetta GLI',
                'Bora',
                'Lupo',
                'Beetle',
                'Scirocco',
                'T-Roc',
                'T-Roc Cabriolet',
                'ID.3',
                'ID.4',
                'ID.5',
                'ID.6',

                // SUVs and Crossovers
                'Tiguan',
                'Tiguan Allspace',
                'T-Roc',
                'T-Roc Cabriolet',
                'Touareg',
                'ID.4',
                'ID.5',
                'ID.6',
                'Atlas',
                'Atlas Cross Sport',
                'Cross Polo',
                'Cross Golf',

                // Electric and Hybrid Vehicles
                'ID.3',
                'ID.4',
                'ID.5',
                'ID.6',
                'ID. Buzz',
                'ID. Buzz Cargo',
                'Golf GTE',
                'Passat GTE',
                'Tiguan eHybrid',
                'Arteon eHybrid',
                'e-up!',
                'e-Golf',
                'Golf TDI Hybrid',
                'Passat GTE',
                'ID. Buzz AD',
                'ID. Vizzion',

                // Performance Models (GTI, R, and RS)
                'Golf GTI',
                'Golf R',
                'Polo GTI',
                'Arteon R',
                'Passat R-Line',
                'Tiguan R',
                'T-Roc R',
                'ID.4 GTX',
                'Golf R Variant',
                'Passat R',
                'Tiguan R-Line',

                // Commercial Vehicles
                'Transporter',
                'Crafter',
                'Amarok',
                'California',
                'Caddy',
                'Caddy Life',
                'Multivan',
                'Caravelle',

                // Classic and Iconic Models
                'Volkswagen Type 1 (Beetle)',
                'Volkswagen Type 2 (Bus)',
                'Volkswagen Type 3',
                'Volkswagen Type 4',
                'Volkswagen Karmann Ghia',
                'Volkswagen Corrado',
                'Volkswagen Fox',

                // Future and Concept Models
                'Volkswagen ID.2',
                'Volkswagen ID.8',
                'ID.Buzz',
                'Volkswagen Nivus',
                'Volkswagen ID.Space Vizzion',
                'Volkswagen ID. Roomzz',

                // Global and Region-Specific Models
                'T-Roc Cabriolet',
                'Golf Alltrack',
                'Golf SportWagen',
                'Jetta GLI',
                'Jetta Hybrid',
                'Vento',
                'Amarok',
                'Polo Sedan',

                // Special and Limited Editions
                'Golf R Variant',
                'Beetle Dune',
                'Jetta GLI Edition',
                'Volkswagen Sport Coupe',
                'ID. Concept',
                'ID. Vision'
            ]
        },
        { make: 'Subaru', models: ['Impreza', 'Legacy', 'WRX', 'BRZ', 'XV', 'Forester', 'Outback', 'Ascent'] },
        {
            make: 'Volvo',
            models: [
                'S60',
                'S60 Recharge',
                'S90',
                'S90 Recharge',
                'V40',
                'V60',
                'V60 Cross Country',
                'V90',
                'V90 Cross Country',
                'C30',
                'C70',
                'V50',
                'S40',
                'V70',
                'S80',

                // SUVs and Crossovers
                'XC40',
                'XC60',
                'XC70',
                'XC90',
                'XC90 Recharge',
                'XC60 Recharge',
                'XC40 Recharge',
                'XC70 Cross Country',
                'V90 Cross Country',

                // Electric and Hybrid Vehicles
                'XC40 Recharge',
                'XC60 Recharge',
                'XC90 Recharge',
                'S60 Recharge',
                'S90 Recharge',
                'V60 Recharge',
                'V90 Recharge',
                'Polestar 1',
                'Polestar 2',

                // Performance Models (Polestar and R-Design)
                'S60 Polestar',
                'S60 R-Design',
                'V60 Polestar',
                'V60 R-Design',
                'XC60 R-Design',
                'XC90 R-Design',
                'Polestar 1',
                'Polestar 2',
                'Polestar 3',
                'Polestar 4',

                // Station Wagons and Estates
                'V40',
                'V60',
                'V60 Cross Country',
                'V70',
                'V90',
                'V90 Cross Country',

                // Classic and Iconic Models
                'Volvo 240',
                'Volvo 740',
                'Volvo 760',
                'Volvo 850',
                'Volvo P1800',
                'Volvo 440',
                'Volvo 460',
                'Volvo 960',
                'Volvo 1800',
                'Volvo 262C',

                // Commercial Vehicles
                'Volvo FH',
                'Volvo FM',
                'Volvo FMX',
                'Volvo FL',
                'Volvo VNL',
                'Volvo VNR',
                'Volvo V90 Cross Country',

                // Future Models and Concepts
                'Volvo Concept Recharge',
                'Volvo 360c',
                'Volvo V60 Cross Country',
                'Volvo V90 Cross Country',
                'Volvo EX90',

                // Special and Limited Editions
                'Volvo S60 Inscription',
                'Volvo XC90 Excellence',
                'Volvo XC60 Inscription',
                'Volvo S90 Ambience',
                'Volvo S60 Momentum'
            ]
        },
        {
            make: 'Peugeot',
            models: [
                '208',
                '208 GTi',
                '308',
                '308 GT',
                '308 SW',
                '508',
                '508 GT',
                '508 SW',
                '3008',
                '3008 GT',
                '4008',
                '5008',
                '5008 GT',
                'Partner',
                'RCZ',

                // SUVs and Crossovers
                '2008',
                '3008',
                '4008',
                '5008',
                'Partner Tepee',
                'Rifter',
                'Peugeot 4007',
                'Peugeot 5008',

                // Electric and Hybrid Vehicles
                'e-208',
                'e-2008',
                'e-Partner',
                'e-Rifter',
                'e-Traveller',
                'Peugeot 3008 Hybrid',
                'Peugeot 508 Hybrid',
                'Peugeot 508 SW Hybrid',
                'Peugeot 3008 Hybrid4',
                'Peugeot 508 PHEV',
                'Peugeot 3008 PHEV',

                // Performance Models (GTi, GT, and PSE)
                '208 GTi',
                '308 GTi',
                '308 GT',
                '508 PSE',
                '3008 GT',
                '508 GT',
                'Peugeot 208 GT',
                'Peugeot 308 GT',
                'Peugeot 308 R Hybrid',
                'Peugeot RCZ R',

                // Commercial Vehicles
                'Peugeot Boxer',
                'Peugeot Expert',
                'Peugeot Partner',
                'Peugeot Traveller',
                'Peugeot Bipper',

                // Classic and Iconic Models
                'Peugeot 205',
                'Peugeot 306',
                'Peugeot 407',
                'Peugeot 604',
                'Peugeot 504',
                'Peugeot 406',
                'Peugeot 404',
                'Peugeot 301',

                // Future Models and Concepts
                'Peugeot e-legend',
                'Peugeot 508 Sport Engineered',
                'Peugeot 208 Electric',
                'Peugeot 3008 Hybrid4',
                'Peugeot 2008 Electric',

                // Special Editions and Variants
                'Peugeot 208 Allure',
                'Peugeot 308 GT Line',
                'Peugeot 5008 GT Line',
                'Peugeot 508 GT Line',
                'Peugeot 208 GT Line'
            ]
        },
        {
            make: 'Renault',
            models: [
                'Clio',
                'Clio RS',
                'Clio Sport Tourer',
                'Zoe',
                'Zoe R110',
                'Megane',
                'Megane RS',
                'Megane Sport Tourer',
                'Laguna',
                'Fluence',
                'Talisman',
                'Captur',
                'Kadjar',
                'Lodgy',
                'Wind',
                'Scenic',
                'Scenic XMOD',
                'Kangoo',
                'Koleos',
                'Espace',
                'Alpine A110',
                'Twingo',
                'Twingo GT',
                'Dokker',

                // SUVs and Crossovers
                'Captur',
                'Kadjar',
                'Koleos',
                'Duster',
                'Kaptur',
                'Kangoo',
                'Espace',
                'Talisman',
                'Arkana',
                'Megane E-Tech',

                // Electric and Hybrid Vehicles
                'Zoe',
                'Zoe R110',
                'Kangoo ZE',
                'Master ZE',
                'Twizy',
                'Twingo Electric',
                'Megane E-Tech Electric',
                'Captur E-Tech Plug-in Hybrid',
                'Kadjar E-Tech',
                'Koleos E-Tech',
                'Clio E-Tech',
                'Renault Kangoo ZE',
                'Renault Zoe ZE',
                'Megane E-Tech',
                'Twingo ZE',

                // Performance Models
                'Megane RS',
                'Clio RS',
                'Twingo RS',
                'Alpine A110',
                'Alpine A110S',
                'Alpine A110 Pure',
                'Renault Sport Spider',
                'Clio Cup',
                'Megane RS Trophy',
                'Megane RS 280',
                'Renault R.S. 01',

                // Commercial and Utility Vehicles
                'Renault Master',
                'Renault Kangoo',
                'Renault Trafic',
                'Renault Dokker',
                'Renault Alaskan',
                'Renault Express',

                // Classic and Iconic Models
                'Renault 4',
                'Renault 5',
                'Renault 16',
                'Renault 18',
                'Renault Fuego',
                'Renault 21',
                'Renault 25',
                'Renault Avantime',

                // Global and Region-Specific Models
                'Renault Kwid',
                'Renault Duster',
                'Renault Captur',
                'Renault Triber',
                'Renault Koleos',
                'Renault Koleos II',
                'Renault Sandero',
                'Renault Logan',
                'Renault Lodgy',

                // Future Models and Concepts
                'Renault Morphoz',
                'Renault EZ-1',
                'Renault EZ-Go',
                'Renault EZ-Pro',
                'Renault EZ-Ultimo',
                'Renault Twizy',
                'Renault Renault 5 Prototype',
                'Renault eVision Concept',
                'Renault Kangoo E-Tech',

                // Special Editions and Variants
                'Renault Alpine GT',
                'Renault Clio RS 16',
                'Renault Captur Initiale Paris',
                'Renault Duster Black Edition',
                'Renault Zoe Trophy',
                'Renault Kadjar Signature'
            ]
        },
        {
            make: 'Land Rover',
            models: [
                'Range Rover',
                'Range Rover Sport',
                'Range Rover Velar',
                'Range Rover Evoque',
                'Discovery',
                'Discovery Sport',
                'Defender',
                'Defender 90',
                'Defender 110',
                'Defender 130',
                'Freelander',
                'Freelander 2',
                'Land Rover Series I',
                'Land Rover Series II',

                // Electric and Hybrid Vehicles
                'Range Rover PHEV',
                'Range Rover Sport PHEV',
                'Range Rover Velar PHEV',
                'Discovery PHEV',
                'Defender PHEV',
                'Range Rover Electric',
                'Defender Electric',

                // Performance Models (SVR, Autobiography, and Special Editions)
                'Range Rover Autobiography',
                'Range Rover SVAutobiography',
                'Range Rover Sport SVR',
                'Defender V8',
                'Defender X',
                'Range Rover Velar R-Dynamic',
                'Defender X-Dynamic',
                'Defender 130 X',

                // Commercial and Utility Vehicles
                'Land Rover Defender 130',
                'Land Rover Defender Hardtop',
                'Land Rover Discovery Commercial',
                'Range Rover LWB',

                // Classic and Iconic Models
                'Land Rover Series I',
                'Land Rover Series II',
                'Land Rover Series III',
                'Range Rover Classic',
                'Defender 90 Classic',

                // Future Models and Concepts
                'Range Rover Velar Electric',
                'Defender 130 Electric',
                'Range Rover Sport Electric',
                'Land Rover Discovery Electric',
                'Land Rover Defender 6x6',
                'Land Rover Defender Electric',

                // Special Editions and Variants
                'Range Rover Westminster',
                'Range Rover LWB',
                'Range Rover HSE',
                'Range Rover SV',
                'Defender 75th Anniversary Edition',
                'Discovery Landmark Edition',
                'Defender V8 Carpathian Edition'
            ]
        },
        {
            make: 'Jaguar',
            models: [
                'XE',
                'XF',
                'XJ',
                'I-PACE',
                'F-Type',
                'X-Type',
                'S-Type',
                'E-Type',
                'F-PACE',
                'XF Sportbrake',
                'XJ220',
                'XJ-S',
                'XJ12',
                'Jaguar XJ LWB',

                // SUVs and Crossovers
                'F-PACE',
                'E-PACE',
                'I-PACE',
                'F-TYPE SVR',
                'Jaguar XJ6',

                // Electric and Hybrid Vehicles
                'I-PACE',
                'Jaguar E-PACE PHEV',
                'Jaguar F-PACE PHEV',
                'Jaguar XE PHEV',
                'Jaguar XF PHEV',
                'Jaguar XJ PHEV',

                // Performance Models (SVR, R-Dynamic, and Special Editions)
                'F-Type SVR',
                'F-Pace SVR',
                'Jaguar XE R-Dynamic',
                'Jaguar XF R-Dynamic',
                'F-Type R',
                'F-Type R-Dynamic',
                'F-PACE R-Dynamic',

                // Classic and Iconic Models
                'Jaguar E-Type',
                'Jaguar XK120',
                'Jaguar XK140',
                'Jaguar XK150',
                'Jaguar Mark II',
                'Jaguar Mark VII',
                'Jaguar XK8',
                'Jaguar XKR',

                // Commercial Vehicles and Special Editions
                'Jaguar XJ220',
                'Jaguar XJ6',
                'Jaguar XF Sportbrake',
                'Jaguar XE Portfolio',
                'Jaguar F-Type Convertible',

                // Future Models and Concepts
                'Jaguar XJ Electric',
                'Jaguar I-Pace Electric',
                'Jaguar Vision Gran Turismo',
                'Jaguar F-Type Electric',
                'Jaguar XE Electric',

                // Special Editions and Variants
                'Jaguar F-Type 75',
                'Jaguar F-Type Chequered Flag Edition',
                'Jaguar XE 300 Sport',
                'Jaguar XF 300 Sport',
                'Jaguar F-Pace First Edition'
            ]
        },
        {
            make: 'Porsche',
            models: [
                '911',
                '911 Carrera',
                '911 Turbo',
                '911 GT3',
                '911 GT2',
                '911 Turbo S',
                '911 Targa',
                '911 Speedster',
                '718 Cayman',
                '718 Boxster',
                '718 Spyder',

                // SUVs and Crossovers
                'Macan',
                'Macan S',
                'Macan Turbo',
                'Macan GTS',
                'Cayenne',
                'Cayenne S',
                'Cayenne Turbo',
                'Cayenne Turbo S',
                'Cayenne GTS',
                'Cayenne Coupe',
                'Cayenne E-Hybrid',
                'Cayenne Turbo E-Hybrid',
                'Cayenne Coupe E-Hybrid',

                // Sedans
                'Panamera',
                'Panamera S',
                'Panamera Turbo',
                'Panamera Turbo S',
                'Panamera 4',
                'Panamera 4S',
                'Panamera E-Hybrid',
                'Panamera GTS',

                // Electric Vehicles
                'Taycan',
                'Taycan 4S',
                'Taycan Turbo',
                'Taycan Turbo S',
                'Taycan Cross Turismo',
                'Taycan GTS',
                'Taycan 4 Cross Turismo',
                'Taycan Turbo Cross Turismo',

                // Performance Models and Special Editions
                '911 R',
                '911 GT3 RS',
                '911 Turbo S Exclusive Series',
                '911 GT2 RS',
                '718 Cayman GT4',
                '718 Boxster Spyder',
                'Cayenne Turbo GT',
                'Panamera Turbo Sport Turismo',
                'Taycan Turbo S Cross Turismo',

                // Classic Models
                'Porsche 356',
                'Porsche 917',
                'Porsche 914',
                'Porsche 924',
                'Porsche 944',
                'Porsche 959',
                'Porsche 928',
                'Porsche 986 Boxster',

                // Commercial Vehicles and Limited Editions
                'Porsche 917 Le Mans',
                'Porsche 911 Dakar',
                'Porsche 935',
                'Porsche 918 Spyder',

                // Future Models and Concepts
                'Porsche Mission E',
                'Porsche 718 Cayman Electric',
                'Porsche Vision GT',

                // Special Editions and Variants
                'Porsche 911 Targa 4S Heritage Edition',
                'Porsche Macan GTS Edition',
                'Porsche 718 Boxster 25 Years',
                'Porsche 911 Turbo S Exclusive Edition',
                'Porsche Panamera Sport Turismo'
            ]
        },
        {
            make: 'Mini',
            models: [
                'Mini Hatch',
                'Mini Hatch Cooper',
                'Mini Cooper S',
                'Mini John Cooper Works',
                'Mini Clubman',
                'Mini Countryman',
                'Mini Countryman Cooper',
                'Mini Countryman SE',
                'Mini Countryman JCW',
                'Mini Paceman',
                'Mini Clubman Cooper',
                'Mini Roadster',
                'Mini Coupe',

                // Electric and Hybrid Vehicles
                'Mini Electric',
                'Mini Cooper SE',
                'Mini Countryman Plug-in Hybrid',
                'Mini Electric PHEV',
                'Mini Electric JCW',

                // Convertibles and Cabriolets
                'Mini Convertible',
                'Mini Cooper Convertible',
                'Mini Cooper S Convertible',
                'Mini John Cooper Works Convertible',

                // Performance Models (John Cooper Works, JCW)
                'Mini John Cooper Works',
                'Mini JCW Clubman',
                'Mini JCW Countryman',
                'Mini JCW GP',

                // Special Editions and Variants
                'Mini 1499 GT',
                'Mini 60 Years Edition',
                'Mini Shadow Edition',
                'Mini Black Roof Edition',
                'Mini Chili Pack',
                'Mini Se7en Edition',
                'Mini Nightfall Edition',
                'Mini Red Hot Edition',
                'Mini Flag Edition',

                // Classic and Iconic Models
                'Mini Classic',
                'Mini Mk1',
                'Mini Mk2',
                'Mini Mk3',
                'Mini Mk4',
                'Mini Mk5',

                // Future Models and Concepts
                'Mini Vision Urbanaut',
                'Mini Electric Roadster Concept',
                'Mini Cooper Electric Concept',
                'Mini Countryman Electric',

                // Commercial and Utility Models
                'Mini Clubvan'
            ]
        },
        { make: 'Lexus', models: ['IS', 'ES', 'GS', 'LS', 'RC', 'LC', 'UX', 'NX', 'RX', 'GX', 'LX'] },
        { make: 'Infiniti', models: ['Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX60', 'QX70', 'QX80'] },
        { make: 'Acura', models: ['ILX', 'TLX', 'RLX', 'RDX', 'MDX', 'NSX'] },
        {
            make: 'Mazda',
            models: [
                'Mazda3',
                'Mazda3 Sedan',
                'Mazda3 Hatchback',
                'Mazda6',
                'Mazda2',
                'Mazda CX-30',
                'Mazda CX-5',
                'Mazda CX-50',
                'Mazda CX-9',
                'Mazda CX-3',

                // Sports Cars and Coupes
                'Mazda MX-5 Miata',
                'Mazda MX-5 RF',
                'Mazda RX-7',
                'Mazda RX-8',
                'Mazda RX-Vision Concept',

                // SUVs and Crossovers
                'Mazda CX-5',
                'Mazda CX-9',
                'Mazda CX-30',
                'Mazda CX-50',
                'Mazda CX-3',

                // Electric and Hybrid Vehicles
                'Mazda MX-30 Electric',
                'Mazda3 Hybrid',
                'Mazda CX-30 Electric',

                // Performance Models (MazdaSpeed, etc.)
                'Mazda3 Mazdaspeed',
                'Mazda6 Mazdaspeed',
                'Mazda MX-5 Miata RF Club',
                'Mazda CX-5 Signature',

                // Classic and Iconic Models
                'Mazda Cosmo',
                'Mazda RX-3',
                'Mazda Familia',
                'Mazda 323',
                'Mazda 626',

                // Future Models and Concepts
                'Mazda Vision Coupe',
                'Mazda MX-30 EV Concept',
                'Mazda RX-9 Concept',

                // Special Editions and Variants
                'Mazda CX-5 Carbon Edition',
                'Mazda3 Carbon Edition',
                'Mazda CX-9 Signature Edition',
                'Mazda MX-5 Miata RF 100th Anniversary Edition',

                // Commercial and Utility Models
                'Mazda B-Series',
                'Mazda BT-50'
            ]
        },
        { make: 'Jeep', models: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'] },
        { make: 'Dodge', models: ['Challenger', 'Charger', 'Durango', 'Journey'] },
        { make: 'Chrysler', models: ['300', 'Pacifica', 'Voyager'] },
        { make: 'Fiat', models: ['500', '500X', '500L', '124 Spider', 'Tipo', 'Doblo', 'Panda', 'Qubo', 'Talento', 'Fullback'] },
        { make: 'Alfa Romeo', models: ['Giulietta', 'Giulia', 'Stelvio', '4C'] },
        { make: 'Maserati', models: ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'GranCabrio'] },
        { make: 'Bentley', models: ['Continental GT', 'Flying Spur', 'Mulsanne', 'Bentayga'] },
        { make: 'Rolls-Royce', models: ['Phantom', 'Ghost', 'Wraith', 'Dawn', 'Cullinan'] },
        { make: 'Lamborghini', models: ['Huracan', 'Aventador', 'Urus'] },
        { make: 'Ferrari', models: ['Portofino', 'Roma', 'F8 Tributo', '812 Superfast', 'GTC4Lusso', 'SF90 Stradale'] },
        { make: 'McLaren', models: ['GT', '570S', '720S', '675LT', '600LT', 'Senna'] },
        { make: 'Bugatti', models: ['Chiron', 'Veyron'] },
        { make: 'Koenigsegg', models: ['Jesko', 'Regera', 'Agera RS'] },
        { make: 'Pagani', models: ['Huayra', 'Zonda'] },
        { make: 'Tesla', models: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Roadster', 'Cybertruck'] },
        { make: 'Lotus', models: ['Elise', 'Exige', 'Evora'] },
        { make: 'Smart', models: ['Fortwo', 'Forfour', 'Roadster'] },
        { make: 'Genesis', models: ['G70', 'G80', 'G90'] },
        { make: 'Datsun', models: ['Go', 'Go+', 'Cross'] },
        { make: 'Mahindra', models: ['Scorpio', 'XUV500', 'Thar', 'KUV100', 'TUV300', 'Marazzo', 'Alturas G4', 'e2o'] },
        { make: 'Tata', models: ['Nano', 'Tiago', 'Tigor', 'Altroz', 'Nexon', 'Harrier', 'Safari', 'Sumo', 'Hexa'] },
        { make: 'Isuzu', models: ['D-Max', 'MU-X'] },
        { make: 'SsangYong', models: ['Tivoli', 'Korando', 'Rexton', 'Rodius', 'Musso'] },
        { make: 'Geely', models: ['Coolray', 'Azkarra', 'Okavango', 'Emgrand', 'LC', 'Panda', 'GC9', 'JL', 'JLX', 'JLX-C'] },
        { make: 'Chery', models: ['Tiggo', 'Arrizo', 'QQ', 'Orinoco', 'Fulwin', 'A1', 'A3', 'A5', 'A9', 'A13', 'A19', 'A21', 'A25', 'A35', 'A44', 'A55', 'A66', 'A88', 'A100', 'A200', 'A500', 'A520', 'A600', 'A800', 'A900', 'A1100'] },
        { make: 'BYD', models: ['Tang', 'Song', 'Yuan', 'Qin', 'Han', 'F3', 'F5', 'F6', 'F7', 'F8', 'F9', 'F0', 'F1', 'F2', 'F3R', 'F6DM', 'G3', 'G5', 'G6', 'G9', 'G6R', 'G6PHEV'] },
        { make: 'Great Wall', models: ['Haval', 'Wingle', 'Coolbear', 'Deer', 'Hover', 'Pegasus', 'Peri', 'Safe', 'Sailor', 'Sing', 'Socool', 'Voleex', 'Wey', 'X200', 'X240', 'Xylo', 'Zotye'] },
        { make: 'JAC', models: ['S2', 'S3', 'S4'] }
    ];
    vehicleTypes = [
        { label: 'Small Car', value: 'Small Car' },
        { label: 'Sedan', value: 'Sedan' },
        { label: 'SUV', value: 'SUV' },
        { label: 'Pickup', value: 'PickUp' },
        { label: 'Coupe', value: 'Coupe' },
        { label: 'Motorcycle', value: 'Motorcycle' },
        { label: 'Van', value: 'Van' },
        { label: 'Truck', value: 'Truck' },
        { label: 'Other', value: 'Other' }
    ];
}
